Update README.md
zhyu/nadia pull request #69
Opened 2018-05-07 03:02 UTC by poligen

from [elixir 1.4 documentation](https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/), Mix v1.4 now automatically infers your applications list as long as you leave the `:applications` key empty. So we should put an explanation for people who use more than version 1.4. Everything works well.

2018-05-28 04:58 UTC, zhyu requested changes

2018-05-28 04:58 UTC, zhyu commented on README.md
> +(you can omit this if your elixir is >= 1.4)
I think we could use more explanation here, e.g.,
"you can leave the `applications` key empty to use [application inference](https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/) if your elixir is >= 1.4"

2018-05-28 08:10 UTC, soanseng reviewed
Cool! much better

2026-06-12 05:37 UTC, zhyu commented
Closing as obsolete against the current README and supported Elixir baseline. The old applications-list note no longer applies to the refreshed project docs.

2026-06-12 05:37 UTC, closed without merging